base_dir: '../datasets_simlink/data_trees/eval_folder' # path to segmentation results to be evaluated
benchmark_forest_path: '../datasets_simlink/data_trees/for_evaluation/benchmark_forest.npy' # path to ground truth benchmark dataset
tree_nums_used_for_evaluation_path: '../datasets_simlink/data_trees/for_evaluation/treenums_used_for_evaluation.npy' # path to numpy array consisting of all tree numbers to be taken into account for evaluation

partitions:
  xy_partition_relative: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1] # radial dvision of each tree into segments (see paper for details)
  z_partition_relative: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1] # vertical dvision of each tree into segments (see paper for details)
  xy_partition_absolute: [0, 1.2, 2.4, 3.6, 4.8, 6, 7.2, 8.4, 9.6, 10.8, 15] # radial dvision of each tree into segments (see paper for details)
  z_partition_absolute: [0, 3.8, 7.6, 11.4, 15.2, 19, 22.8, 26.6, 30.4, 34.2, 40] # vertical dvision of each tree into segments (see paper for details)