default_args: ["configs/_modular/model.yaml", "configs/_modular/dataset_train.yaml", "configs/_modular/dataset_test.yaml"]


############ modification of default args
dataset_train:
  data_root: '../datasets_simlink/data_trees/training_data_finetune/random_crops_all_valid_ones'

model:
  spatial_shape: [500, 500, 1000]

############ non-default args
dataloader:
  train:
    batch_size: 4
    num_workers: 2
  test:
    batch_size: 2
    num_workers: 2

optimizer:
  type: 'AdamW'
  lr: 0.0004
  weight_decay: 0.001

scheduler:
  t_initial: 25
  lr_min: 0.000005
  cycle_decay: 1
  warmup_lr_init: 0.00001
  warmup_t: 0
  cycle_limit: 1
  t_in_epochs: True

epochs: 25
examples_per_epoch: 500
fp16: True
pretrain: '../work_dirs/train_pointwise/epoch_880.pth'
grad_norm_clip: True

# validation args
save_frequency: 1
validation_frequency: 1
