# default_args is used to include configs from the _modular folder into this config. This ensures a modular way of combining different config files.
# Individual entries of the loaded default args can be changed by simply redefining them as is done below under 'modification of default args'
default_args: ["configs/_modular/model.yaml", "configs/_modular/dataset_train.yaml", "configs/_modular/dataset_test.yaml"]


############ modification of default args
model: 
  mode: 'classifier'
  use_feats: True
  dim_feat: 32
  num_blocks: 3
  max_num_points_per_voxel: 100
  spatial_shape: ~

dataset_train:
  data_root: '../datasets_simlink/data_trees/training_data/classifier_data'
  data_augmentations: 
    jitter: False
    flip: False
    rot: False
    scaled: False
    point_jitter: False


############ non-default args
dataloader:
  train:
    batch_size: 16
    num_workers: 2
  test:
    batch_size: 2
    num_workers: 2


optimizer:
  type: 'AdamW'
  lr: 0.0001
  weight_decay: 0.001


scheduler: # learning rate scheduler arguments (see https://timm.fast.ai/schedulers for details)
  t_initial: 50
  lr_min: 0.0000001
  cycle_decay: 1
  warmup_lr_init: 0.000006
  warmup_t: 0
  cycle_limit: 1
  t_in_epochs: True

epochs: 50 # number of epochs to train
examples_per_epoch: 128 # number of examples (crops/trees for pointwise and classification training respectively) to use per epoch
fp16: True # using half precision for network prediction
pretrain: ~ # path to pretrained network parameters
grad_norm_clip: True # gradient clipping to avoid excessive gradient magnitude

# validation args
save_frequency: 1 # save frequency of state dict
validation_frequency: 10000 # validation frequency (set to 10000 here since no validation is performed for training of classifier)