default_args: ["configs/_modular/model.yaml", "configs/_modular/dataset_train.yaml", "configs/_modular/dataset_test.yaml"]


############ modification of default args
model:
  mode: 'classifier'
  use_feats: True
  dim_feat: 32
  num_blocks: 2
  max_num_points_per_voxel: 100

dataset_train:
  data_root: '../datasets_simlink/data_trees/training_data/classifier_data'
  data_augmentations: 
    jitter: False
    flip: False
    rot: False
    scaled: False
    point_jitter: False


############ non-default args
dataloader:
  train:
    batch_size: 16
    num_workers: 2
  test:
    batch_size: 2
    num_workers: 2


optimizer:
  type: 'AdamW'
  lr: 0.0005
  weight_decay: 0.001


scheduler:
  t_initial: 50
  lr_min: 0.000001
  cycle_decay: 1
  warmup_lr_init: 0.000006
  warmup_t: 0
  cycle_limit: 1
  t_in_epochs: True

epochs: 50
examples_per_epoch: 128
fp16: True
pretrain: ~
grad_norm_clip: True

# validation args
save_frequency: 1
validation_frequency: 10000