default_args: ["configs/_modular/model.yaml", "configs/_modular/dataset_test.yaml"]

########################### modification of default args
dataset_test:
  data_root: '../datasets_simlink/data_trees/test/tiles/L1W'

########################### other args
base_dir: '../datasets_simlink/data_trees/eval_treelearn'

dataloader:
    batch_size: 1
    num_workers: 1

path_checkpoint_to_use_for_y_greater_zero: 'work_dirs/train_pointwise/epoch_1200.pth' # best checkpoint for y NOT greater zero
path_checkpoint_to_use_for_y_not_greater_zero: 'work_dirs/train_pointwise/epoch_880.pth' # best checkpoint for y greater zero