default_args: ["configs/_modular/model.yaml", "configs/_modular/dataset_test.yaml"]

########################### modification of default args
dataset_test:
  data_root: '../datasets_simlink/data_trees/test/tiles/L1W'

########################### other args
base_dir: '../datasets_simlink/data_trees/eval_treelearn_finetuned_less_epoch'

dataloader:
    batch_size: 1
    num_workers: 1

# path_checkpoint_to_use_for_y_greater_zero: 'work_dirs/finetune_pointwise_all_data/epoch_19.pth'
# path_checkpoint_to_use_for_y_not_greater_zero: 'work_dirs/finetune_pointwise_all_data/epoch_19.pth'
path_checkpoint_to_use_for_y_greater_zero: 'work_dirs/finetune_pointwise_best_ysmaller/epoch_10.pth'
path_checkpoint_to_use_for_y_not_greater_zero: 'work_dirs/finetune_pointwise_best_ygreater/epoch_10.pth'